using System.Xml.Serialization;
using AvaloniaUI.Helpers;
using XsdGen;

namespace AvaloniaUITest;

/// <summary>
/// This tests the code-generation for the schema file:
/// Reading a .siml file
/// Validating a .siml file
///
/// This is performed using "XmlSerializer compatible C# classes", generated by tool "XmlSchemaClassGenerator".
/// <see href="https://github.com/mganss/XmlSchemaClassGenerator"/>.
/// </summary>
[TestClass]
public class TestSchemaCodeGen : TestSchemaBase
{
    [TestMethod]
    [DataRow("Artak_Sample_March_04.xsd", "MarksServiceTest.siml")]
    public void TestReadSimlFile(string schemaFileName, string serviceFileName)
    {
        //----------------------------------
        // Note:
        // serializer.Deserialize(fs) is nothing but a wrapper around XmlReader.Create ( )
        // See: TestValidateServiceViaSchema !!!!!
        //----------------------------------
        
        var serializer = new XmlSerializer(typeof(ServiceInterface));
        
        // If the XML document has been altered with unknown nodes or attributes, handle them with the
        // UnknownNode and UnknownAttribute events.
        serializer.UnknownNode += Serializer_UnknownNode;
        serializer.UnknownAttribute += Serializer_UnknownAttribute;

        var filename = $@"{TestFilesPath}\{serviceFileName}";
        var fs = new FileStream(filename, FileMode.Open);

        var si = serializer.Deserialize(fs) as ServiceInterface;
        si?.PrintServiceInterface();
    }

    private void Serializer_UnknownNode(object? sender, XmlNodeEventArgs e)
    {
        NumErrorsFound++;

        Console.WriteLine("Unknown Node:" + e.Name + "\t" + e.Text);
    }

    private void Serializer_UnknownAttribute(object? sender, XmlAttributeEventArgs e)
    {
        NumErrorsFound++;

        var attr = e.Attr;
        Console.WriteLine("Unknown attribute " + attr.Name + "='" + attr.Value + "'");
    }
}