using System.Xml.Schema;
using AvaloniaUI.Helpers;
using FluentAssertions;

namespace AvaloniaUITest;

/// <summary>
/// This tests the code-generation for the schema file:
/// Reading a .siml file
/// Validating a .siml file
///
/// This is performed using "XmlSerializer compatible C# classes", generated by tool "XmlSchemaClassGenerator".
/// <see href="https://github.com/mganss/XmlSchemaClassGenerator"/>.
/// </summary>
[TestClass]
public class TestSchemaCodeGen : TestSchemaBase
{
    [TestMethod]
    [DataRow("Artak_Sample_March_04.xsd", "MarksServiceTest.siml")]
    public void TestReadAndValidateSimlFile(string schemaFileName, string serviceFileName)
    {
        var schemaSet = CreateSchemaSet($@"{TestFilesPath}\{schemaFileName}");
        var xDocument = CreateDocument($@"{TestFilesPath}\{serviceFileName}");

        xDocument.Should().NotBeNull();
        xDocument.Validate(schemaSet, ValidationEventHandler);

        var serviceInterface = CreateServiceInterface(xDocument, Serializer_UnknownNode, Serializer_UnknownAttribute);
        serviceInterface.Should().NotBeNull();
        serviceInterface?.PrintServiceInterface();
    }
}