//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1107.0 using the following command:
// xscgen --namespace=XsdGen --nullable Copied_Artak_Sample_March_04.xsd
namespace XsdGen
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValidTypes", Namespace="")]
    public enum ValidTypes
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("bool")]
        Bool,
        
        [System.Xml.Serialization.XmlEnumAttribute("char")]
        Char,
        
        [System.Xml.Serialization.XmlEnumAttribute("int8")]
        Int8,
        
        [System.Xml.Serialization.XmlEnumAttribute("uint8")]
        Uint8,
        
        [System.Xml.Serialization.XmlEnumAttribute("int16")]
        Int16,
        
        [System.Xml.Serialization.XmlEnumAttribute("uint16")]
        Uint16,
        
        [System.Xml.Serialization.XmlEnumAttribute("int32")]
        Int32,
        
        [System.Xml.Serialization.XmlEnumAttribute("uint32")]
        Uint32,
        
        [System.Xml.Serialization.XmlEnumAttribute("int64")]
        Int64,
        
        [System.Xml.Serialization.XmlEnumAttribute("unt64")]
        Unt64,
        
        [System.Xml.Serialization.XmlEnumAttribute("type_id")]
        TypeId,
        
        [System.Xml.Serialization.XmlEnumAttribute("float32")]
        Float32,
        
        [System.Xml.Serialization.XmlEnumAttribute("float64")]
        Float64,
        
        String,
        
        BinaryBuffer,
        
        DateTime,
        
        SomeStruct,
        
        SomeEnum,
        
        SomeArray,
        
        [System.Xml.Serialization.XmlEnumAttribute("NEMemory::uAlign")]
        NeMemoryUAlign,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValidObjects", Namespace="")]
    public enum ValidObjects
    {
        
        Enumerate,
        
        Structure,
        
        Imported,
        
        DefinedType,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterface", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ServiceInterface", Namespace="")]
    public partial class ServiceInterface
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Overview")]
        public ServiceInterfaceOverview Overview { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType> _dataTypeList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("DataTypeList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("DataType")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType> DataTypeList
        {
            get
            {
                return _dataTypeList;
            }
            private set
            {
                _dataTypeList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterface" /> class.</para>
        /// </summary>
        public ServiceInterface()
        {
            this._dataTypeList = new System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType>();
            this._attributeList = new System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute>();
            this._methodList = new System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod>();
            this._constantList = new System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant>();
            this._includeList = new System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute> _attributeList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("AttributeList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute> AttributeList
        {
            get
            {
                return _attributeList;
            }
            private set
            {
                _attributeList = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod> _methodList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("MethodList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Method")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod> MethodList
        {
            get
            {
                return _methodList;
            }
            private set
            {
                _methodList = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant> _constantList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("ConstantList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Constant")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant> ConstantList
        {
            get
            {
                return _constantList;
            }
            private set
            {
                _constantList = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation> _includeList;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("IncludeList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Location")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation> IncludeList
        {
            get
            {
                return _includeList;
            }
            private set
            {
                _includeList = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("FormatVersion", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string FormatVersion { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceOverview", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceOverview
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Version", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Version { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("isRemote", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsRemote { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType> _dataType;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DataType")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType> DataType
        {
            get
            {
                return _dataType;
            }
            private set
            {
                _dataType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceDataTypeList" /> class.</para>
        /// </summary>
        public ServiceInterfaceDataTypeList()
        {
            this._dataType = new System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataType", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeListDataType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private ServiceInterfaceDataTypeListDataTypeContainer _container = XsdGen.ServiceInterfaceDataTypeListDataTypeContainer.Array;
        
        [System.ComponentModel.DefaultValueAttribute(XsdGen.ServiceInterfaceDataTypeListDataTypeContainer.Array)]
        [System.Xml.Serialization.XmlElementAttribute("Container")]
        public ServiceInterfaceDataTypeListDataTypeContainer Container
        {
            get
            {
                return _container;
            }
            set
            {
                _container = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("BaseTypeValue")]
        public string BaseTypeValue { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("BaseTypeKey")]
        public ValidTypes BaseTypeKeyValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BaseTypeKey property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BaseTypeKeyValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<ValidTypes> BaseTypeKey
        {
            get
            {
                if (this.BaseTypeKeyValueSpecified)
                {
                    return this.BaseTypeKeyValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BaseTypeKeyValue = value.GetValueOrDefault();
                this.BaseTypeKeyValueSpecified = value.HasValue;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.Xml.Serialization.XmlElementAttribute("Namespace")]
        public string Namespace { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public string Location { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldList> _fieldList;
        
        [System.Xml.Serialization.XmlElementAttribute("FieldList")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldList> FieldList
        {
            get
            {
                return _fieldList;
            }
            private set
            {
                _fieldList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FieldList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FieldListSpecified
        {
            get
            {
                return (this.FieldList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceDataTypeListDataType" /> class.</para>
        /// </summary>
        public ServiceInterfaceDataTypeListDataType()
        {
            this._fieldList = new System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldList>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Type", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ValidObjects Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Values", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Values { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataTypeContainer", Namespace="", AnonymousType=true)]
    public enum ServiceInterfaceDataTypeListDataTypeContainer
    {
        
        Array,
        
        LinkedList,
        
        HashMap,
        
        Pair,
        
        CustomContainer,
        
        [System.Xml.Serialization.XmlEnumAttribute("New Type")]
        NewType,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataTypeFieldList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeListDataTypeFieldList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListEnumEntry> _enumEntry;
        
        [System.Xml.Serialization.XmlElementAttribute("EnumEntry")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListEnumEntry> EnumEntry
        {
            get
            {
                return _enumEntry;
            }
            private set
            {
                _enumEntry = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the EnumEntry collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnumEntrySpecified
        {
            get
            {
                return (this.EnumEntry.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceDataTypeListDataTypeFieldList" /> class.</para>
        /// </summary>
        public ServiceInterfaceDataTypeListDataTypeFieldList()
        {
            this._enumEntry = new System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListEnumEntry>();
            this._field = new System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListField>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListField> _field;
        
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceDataTypeListDataTypeFieldListField> Field
        {
            get
            {
                return _field;
            }
            private set
            {
                _field = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Field collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FieldSpecified
        {
            get
            {
                return (this.Field.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataTypeFieldListEnumEntry", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeListDataTypeFieldListEnumEntry
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataTypeFieldListField", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeListDataTypeFieldListField
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public ServiceInterfaceDataTypeListDataTypeFieldListFieldValue Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("DataType", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string DataType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceDataTypeListDataTypeFieldListFieldValue", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceDataTypeListDataTypeFieldListFieldValue
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDefault", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDefaultValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDefault property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDefaultValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDefault
        {
            get
            {
                if (this.IsDefaultValueSpecified)
                {
                    return this.IsDefaultValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDefaultValue = value.GetValueOrDefault();
                this.IsDefaultValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceAttributeList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceAttributeList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute> _attribute;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Attribute")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute> Attribute
        {
            get
            {
                return _attribute;
            }
            private set
            {
                _attribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceAttributeList" /> class.</para>
        /// </summary>
        public ServiceInterfaceAttributeList()
        {
            this._attribute = new System.Collections.ObjectModel.Collection<ServiceInterfaceAttributeListAttribute>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceAttributeListAttribute", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceAttributeListAttribute
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("DataType", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string DataType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: Always|OnChange.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("Always|OnChange")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Notify", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Notify { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceMethodList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceMethodList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod> _method;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Method")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod> Method
        {
            get
            {
                return _method;
            }
            private set
            {
                _method = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceMethodList" /> class.</para>
        /// </summary>
        public ServiceInterfaceMethodList()
        {
            this._method = new System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethod>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceMethodListMethod", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceMethodListMethod
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter> _paramList;
        
        [System.Xml.Serialization.XmlArrayAttribute("ParamList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter> ParamList
        {
            get
            {
                return _paramList;
            }
            private set
            {
                _paramList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ParamList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParamListSpecified
        {
            get
            {
                return (this.ParamList.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceMethodListMethod" /> class.</para>
        /// </summary>
        public ServiceInterfaceMethodListMethod()
        {
            this._paramList = new System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: request|response|broadcast.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("request|response|broadcast")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("MethodType", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string MethodType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Response", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Response { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceMethodListMethodParamList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceMethodListMethodParamList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter> _parameter;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter> Parameter
        {
            get
            {
                return _parameter;
            }
            private set
            {
                _parameter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceMethodListMethodParamList" /> class.</para>
        /// </summary>
        public ServiceInterfaceMethodListMethodParamList()
        {
            this._parameter = new System.Collections.ObjectModel.Collection<ServiceInterfaceMethodListMethodParamListParameter>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceMethodListMethodParamListParameter", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceMethodListMethodParamListParameter
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public ServiceInterfaceMethodListMethodParamListParameterValue Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("DataType", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string DataType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceMethodListMethodParamListParameterValue", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceMethodListMethodParamListParameterValue
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDefault", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDefault { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceConstantList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceConstantList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant> _constant;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Constant")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant> Constant
        {
            get
            {
                return _constant;
            }
            private set
            {
                _constant = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceConstantList" /> class.</para>
        /// </summary>
        public ServiceInterfaceConstantList()
        {
            this._constant = new System.Collections.ObjectModel.Collection<ServiceInterfaceConstantListConstant>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceConstantListConstant", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceConstantListConstant
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("DataType", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ValidTypes DataType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: [A-Za-z][A-Za-z_0-9]+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Za-z][A-Za-z_0-9]+")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceIncludeList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceIncludeList
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation> _location;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("Location")]
        public System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation> Location
        {
            get
            {
                return _location;
            }
            private set
            {
                _location = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ServiceInterfaceIncludeList" /> class.</para>
        /// </summary>
        public ServiceInterfaceIncludeList()
        {
            this._location = new System.Collections.ObjectModel.Collection<ServiceInterfaceIncludeListLocation>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1107.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ServiceInterfaceIncludeListLocation", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ServiceInterfaceIncludeListLocation
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DeprecateHint")]
        public string DeprecateHint { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ID", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Id { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("Name", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("IsDeprecated", Namespace="", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDeprecatedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsDeprecated property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsDeprecatedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsDeprecated
        {
            get
            {
                if (this.IsDeprecatedValueSpecified)
                {
                    return this.IsDeprecatedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsDeprecatedValue = value.GetValueOrDefault();
                this.IsDeprecatedValueSpecified = value.HasValue;
            }
        }
    }
}
