//
// AregtechTest.cs
//
// This file was generated by XMLSpy 2024 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using Altova.Types;

namespace Aregtech
{
	/// <summary>
	/// Summary description for AregtechTest.
	/// </summary>
	class AregtechTest
	{
		protected static void Example()
		{
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save an XML document:
			//   Aregtech2 doc = Aregtech2.CreateDocument();
			//   // Append root element
			//   ServiceInterfaceType root = doc.ServiceInterface.Append();
			//   // Append root element with prefix
			//   // ServiceInterfaceType root = doc.ServiceInterface.AppendWithPrefix("p");
			//   // Declare all namespaces from schema on root element 
			//   Aregtech2.DeclareAllNamespacesFromSchema(root);
			//   // Declare namespaces on element 
			//   root.DeclareNamespace("ns1", "http://NamespaceTest.com/ns1");
			//   ...
			//   doc.SaveToFile("Aregtech1.xml", true);
			//
			// Example code to load and save an XML document:
			//   Aregtech2 doc = Aregtech2.LoadFromFile("Aregtech1.xml");
			//   ServiceInterfaceType root = doc.ServiceInterface.First;
			//   ...
			//   doc.SaveToFile("Aregtech1.xml", true);
		}

		/// <summary>
		/// The main entry point for the application.
		/// </summary>
		[STAThread]
		public static int Main(string[] args)
		{
			try
			{
				Console.WriteLine("Aregtech Test Application");
				Example();
				Console.WriteLine("OK");
				return 0;
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
				return 1;
			}
		}
	}
}
