#ifndef LUSAN_VIEW_LOG_SCOPEOUTPUTVIEWER_HPP
#define LUSAN_VIEW_LOG_SCOPEOUTPUTVIEWER_HPP
/************************************************************************
 *  This file is part of the Lusan project, an official component of the AREG SDK.
 *  Lusan is a graphical user interface (GUI) tool designed to support the development,
 *  debugging, and testing of applications built with the AREG Framework.
 *
 *  Lusan is available as free and open-source software under the MIT License,
 *  providing essential features for developers.
 *
 *  For detailed licensing terms, please refer to the LICENSE.txt file included
 *  with this distribution or contact us at info[at]aregtech.com.
 *
 *  \copyright   © 2023-2024 Aregtech UG. All rights reserved.
 *  \file        lusan/view/log/ScopeOutputViewer.hpp
 *  \ingroup     Lusan - GUI Tool for AREG SDK
 *  \author      Artak Avetyan
 *  \brief       Lusan application, Scope output viewer widget.
 *
 ************************************************************************/

#include "lusan/view/common/OutputWindow.hpp"
#include "areg/component/NEService.hpp"

class ScopeLogViewerFilter;
class LoggingModelBase;

class QTableView;

namespace Ui {
    class ScopeOutputViewer;
}

class ScopeOutputViewer : public OutputWindow
{
    Q_OBJECT

public:
    ScopeOutputViewer(MdiMainWindow* wndMain, QWidget* parent = nullptr);
    virtual ~ScopeOutputViewer(void);
    
public:
    
    void setupFilter(LoggingModelBase* logModel, uint32_t scopeId, uint32_t sessionId, ITEM_ID instance);
    
    void setupFilter(LoggingModelBase* logModel, const QModelIndex& index);
    
private:
    inline QTableView* ctrlTable(void) const;

private:
    Ui::ScopeOutputViewer*  ui; //!< The user interface object, generated by Qt Designer
    ScopeLogViewerFilter*   mFilter;
    LoggingModelBase*       mLogModel;
};

#endif  // LUSAN_VIEW_LOG_SCOPEOUTPUTVIEWER_HPP
